name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: find vcpkg
      run: |
        Get-ChildItem . -Recurse | Select-String "vcpkg"
        

    - name: Add msbuild to PATH (include NuGet, vcpkg)
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Add NuGet to PATH
      uses: nuget/setup-nuget@v1
    - name: Install dependencies from NuGet
      run: nuget install Grasshopper

    # - name: Download dependency lib. LibIGL, Eigen
    #   run: |
    #     git clone https://github.com/libigl/libigl.git ./external/libigl
    #     git clone https://gitlab.com/libeigen/eigen.git ./external/eigen
    #     set ILink_LibraryPath="./external/libigl/include;./external/eigen"
    - name: bootstrap-vcpkg
      run: |
        get-command bootstrap-vcpkg
        #bootstrap-vcpkg
        #dir

    - name: Install  eigen3 libigl
      run: |
        vcpkg install eigen3 libigl
        dir
        dir C:\vcpkg
        dir C:\vcpkg\installed
        dir C:\vcpkg\installed\vcpkg
        dir C:\vcpkg\installed\x86-windows
        dir C:\vcpkg\installed\x86-windows\include
        

    - name: integrate install
      run: |
        vcpkg integrate install
        Get-ChildItem . -Recurse | Select-String "vcpkg"
        
    - name: find vcpkg
      run: |
        Get-ChildItem . -Recurse | Select-String "vcpkg"
        
    - name: install Grasshopper
      run: |
        nuget install Grasshopper

    - name: Build
      env:
        VCPKG_ROOT: C:\vcpkg
      run: |
         $env:VCPKG_ROOT
         msbuild
#       run: msbuild /p:IncludePath="./external/libigl/include"
      #run: msbuild /p:IncludePath="external/eigen;external/libigl/include
